mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', include("users.urls"))
]

mysite/polls/urls.py
from django.urls import path
from .  import views
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/users/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("signup", views.signup_view, name="signup"),
    path("", views.main_site, name="main_site")
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    student_id = models.CharField(max_length=10)
    my_money = models.CharField(max_length=10)

mysite/polls/views.py
# from django.shortcuts import render
from django.http import HttpResponse
from .models import Question

# Create your views here.

def index(request):
    # return HttpResponse("Hello, World.")
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    output = ', '.join([q.question_text for q in latest_question_list])
    return HttpResponse(output)

def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

mysite/users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from .models import User

# global my_money
# my_money = 0
# Create your views here.

def main_site(request):
    return render(request, "users/main.html")


def signup_view(request):
    try:
        if request.method == "POST":
            username = request.POST["username"]
            password = request.POST["password"]
            firstname = request.POST["firstname"]
            lastname = request.POST["lastname"]
            email = request.POST["email"]
            student_id = request.POST["student_id"]
            my_money = request.POST["my_money"]
            user = User.objects.create_user(username, email, password)
            user.last_name = lastname
            user.first_name = firstname
            user.student_id = student_id
            user.my_money = my_money
            user.save()

            return redirect("user:login")
    except:
        return render(request, "users/error.html")

    return render(request, "users/signup.html")

def login_view(request):
    nn =[]
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        use_money = request.POST["use_money"]
        add_money = request.POST["add_money"]
        user = authenticate(username=username, password=password)
        # user_money = User.objects.values('username')
        user_name = User.objects.values_list()
        for i in user_name:
            if username in i:
                nn.append(i)
        for final in nn:
            my_money = int(final[-1])
        if user is not None:
            print("인증성공")
            final_money = str(my_money - int(use_money) + int(add_money))
            user.use_money = use_money
            user.final_money = final_money
            user.my_money = final_money
            user.add_money = add_money
            user.save()
            login(request, user)
        else:
            print("인증실패")
    return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    return redirect("user:login")

mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li><a href="/polls/{{question.id}}/">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/users/templates/users/error.html
<html>
    <head>
    <title>정보가 중복됩니다.</title>

    <script type="text/javascript">
    
      alert("아이디가 중복됩니다 다시해주세요.");
    //   document.location.href="users/templates/signup.html";
    history.go(-1);
    
    </script>
    
     
    
    </head>
    
    <body>
    </body>
</html>
    
    

mysite/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="text-align:center; color:white; background-color: black;">
    <br>
    {% if user.is_authenticated %}
        로그인 성공!
        {{ user.username }}님 환영합니다.
    </br>
    <br>
        {{ user.username }}님의 통장 잔액은 {{user.my_money}}원
    </br>
    <br>
        사용한 금액은 {{user.use_money}}원
    </br>
    <br>
        추가된 금액은 {{user.add_money}}
    </br>
    <br>
        남은 금액은 {{user.final_money}}원 입니다)
    </br>

    


    <a href="{% url 'user:logout' %}">로그아웃</a>
    {% else %}

    <form action="" method="POST" style="text-align: center;">
        {% csrf_token %}
        <input name="username" type="text"> 아이디
        <input name="password" type="password"> 비밀번호
        <input name="use_money" type="number"> 사용한 금액
        <input name="add_money" type="number"> 추가될 금액
        <input type="submit" value="로그인">
    </form>
    <a href="{% url 'user:signup' %}">회원가입</a>

    {% endif %}
    
</body>
</html>

mysite/users/templates/users/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="../../static/users/main.css">
    <title>payhere</title>
</head>
<body>
    <a href="http://127.0.0.1:8000/login" style="text-align: center;">
        <span>👇</span>
        pay here
    </a>
</body>
</html>

mysite/users/templates/users/signup.html
회원가입 페이지
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원가입</title>
</head>
<body style="text-align: center; background-color: black; color:white;">
    <form action=" " method="POST">
        {% csrf_token %}
        <p>아이디</p>
        <input name ="username" type="text">
        <p>비밀번호</p>
        <input name = "password" type="password">
        <p>성</p>
        <input name = "firstname" type="text">
        <p>이름</p>
        <input name = "lastname" type="text">
        <p>이메일</p>
        <input name = "email" type="text">
        <p>나이</p>
        <input name="student_id" type="text">
        <p>자산</p>
        <input name="my_money" type="number">
        <input type="submit" value ="회원가입">
    </form>    
</body>
</html>